### ISSUE TITLE
Display no answers between the single questions

### ISSUE THREAD

**Issue by StevoGonzales** [zechendorf/easyquiz#4]
Is it possible to skip the intermediate step between the single questions, where the answer for each question is displayed.
I just want to go from one question to the next with one single result (page) at the end of the whole quiz.
Thanks in advance.
Stevo

**Comment by zechendorf** [comment]
Yes of course. I can make it configureable in the plugin settings.

I don't know yet when I'll be able to implement this.

**Comment by zechendorf** [comment]
@StevoGonzales - If you'd like to sponsor the development I could speed up the implementation.

**Comment by StevoGonzales** [comment]
Oh, sounds great. 
We would like to sponsor. Until when could it be implemented?
How would we going on?
Regards.

**Comment by zechendorf** [comment]
You can sponsor via bitcoin (https://blockchain.info/address/1MPwCTNEKiUAXJncvHB7DrAvF2mWiQJWct) or paypal (christopher@zechendorf.com) - feel free to give any amount you deem fair.

I would extend the Quiz-Object so that there is a checkbox that (when checked) prevents the answers to be shown. Clicking on "submit" will thus redirect you directly to the next question.

I can do this early next week.

**Comment by StevoGonzales** [comment]
Can we get an invoice for that?

**Comment by zechendorf** [comment]
Absolutely.

**Comment by zechendorf** [comment]
If you provide me with a VAT ID I can ommit the VAT (Germany: 19%).

**Comment by zechendorf** [comment]
@StevoGonzales it is now possible to configure that no answers should be displayed.

To do this: Edit the plugin content element and check "do not show answers" under "plugin options".

![bildschirmfoto vom 2017-05-05 14-08-07](https://cloud.githubusercontent.com/assets/11517177/25744885/72b8cd32-319c-11e7-897e-5116c3fd2cb0.png)
